### ISSUE TITLE
Error: ENOENT: no such file or directory open '...../hammerhead.min.js'

### ISSUE THREAD

**Issue by Abnumality** [binary-person/rammerhead#1]
```
Error: ENOENT: no such file or directory, open 'C:\Users\MYNAME\rammerhead\src\client\hammerhead.min.js'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at RammerheadProxy.GET (C:\Users\MYNAME\rammerhead\src\classes\RammerheadProxy.js:541:34)
    at RammerheadProxy._registerServiceRoutes (C:\Users\MYNAME\rammerhead\node_modules\testcafe-hammerhead\lib\proxy\index.js:96:14)
    at new Proxy (C:\Users\MYNAME\rammerhead\node_modules\testcafe-hammerhead\lib\proxy\index.js:65:14)
    at new RammerheadProxy (C:\Users\MYNAME\rammerhead\src\classes\RammerheadProxy.js:124:13)
    at Object.<anonymous> (C:\Users\MYNAME\rammerhead\src\server\index.js:17:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\MYNAME\rammerhead\src\server.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\MYNAME\\rammerhead\\src\\client\\hammerhead.min.js'
```
its looking like there's some files missing? i'm not too sure.

**Comment by binary-person** [comment]
you need to run the build step first: `npm run build` before you start it
