### ISSUE TITLE
replit token error

### ISSUE THREAD

**Issue by whyisthesheep** [binary-person/rammerhead#13]
when I run everything on replit after installing etc it prints this:
`About to throw: Unexpected token '.'
/home/runner/rammerhead/src/util/addUrlShuffling.js:69
        disableShuffling = pattern.urlAttr?.toLowerCase() === 'action';
                                           ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/rammerhead/src/classes/RammerheadProxy.js:17:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/rammerhead/src/server/index.js:4:25)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
exit status 7`

**Comment by binary-person** [comment]
please follow #14 for updates
